### ISSUE TITLE
enable pre-commit

### ISSUE THREAD

**Issue by vidiecan** [dataquest-dev/DSpace#48]
add https://pre-commit.com/

e.g., 
.pre-commit-config.yaml

```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-json
    - id: mixed-line-ending
      args: ['--fix=lf']
      description: Forces to replace line ending by the UNIX 'lf' character.
    - id: check-added-large-files
      args: ['--maxkb=5000']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-added-large-files
        args:
        - --maxkb=10000
        - --enforce-all
-   repo: https://github.com/crate-ci/typos
    rev: v1.6.0
    hooks:
    -   id: typos
        types_or: [python,c,c++]
        exclude: '^(_tests/data|_tests/quality|_tests/pylibs|_tests/unittests-c\+\+/catch.hpp|_tests/unittests-c\+\+/_dirent.h|tools/pybind11|\.github|src/unilib|src/tsl|src/text/re2|src/serialize/json|src/format|src/forms/ib/ignorant|_tests/tools/pdf_anonym_bg.py|src/nlp/stemmer.cpp)'
        args:
        - --write-changes
        - --config=.typos.toml 
```
